### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by icoric4** [dennisbappert/u-2-net-portrait#2]
Hello and thank you for the great work! 

It seems that I can't find the pretrained model anywhere. Would you be so kind and point me to it? 

Thanks!

**Comment by dbpprt** [comment]
Hello @icoric4,

thanks for pointing it out, the markdown in the README.md was broken, I fixed the link but [here](https://1drv.ms/u/s!Am46hiIqzupmhq5V_Zt36ACGjmI6Xg?e=WPhq7y) you go.

**Comment by icoric4** [comment]
Thanks!

**Comment by dbpprt** [comment]
I will soon publish a new model in a separate repository, probably also one checkpoint trained on matting.
