### ISSUE TITLE
Real time webcam background matting?

### ISSUE THREAD

**Issue by benbro** [dennisbappert/u-2-net-portrait#3]
Is it fast enough to replace webcam background in real time?
Can I run it in the browser with tensorflow.js?
Is there online demo similar to the MODNet [demo](https://gradio.app/g/modnet) and [notebook](https://colab.research.google.com/drive/1Pt3KDSc2q7WxFvekCnCLD8P0gBEbxm6J?usp=sharing)?

**Comment by dbpprt** [comment]
Hey @benbro,

it will probably not run in realtime and I did not explore any options for e.g. tensorflow.js, additional demos, ...

I'm open for PRs though 👍

**Comment by benbro** [comment]
Thanks
