### ISSUE TITLE
The model is in the train mode in demo

### ISSUE THREAD

**Issue by dfrumkin** [dennisbappert/u-2-net-portrait#4]
Hello!
Why is the model put into train mode in the demo?
https://github.com/dennisbappert/u-2-net-portrait/blob/master/demo.py#L78
The difference between train() and eval() is huge actually.

**Comment by dbpprt** [comment]
Good catch, this is actually a bug. I will fix it, thanks for raising.

**Comment by dbpprt** [comment]
Fixed.
